BULLET_WIDTH = 2
BULLET_HEIGHT = 8
BULLET_COLOR = 9
BULLET_SPEED = 4

ENEMY_WIDTH = 8
ENEMY_HEIGHT = 8
ENEMY_SPEED = 1.5

GUNSHOT_START_RADIUS = 1
GUNSHOT_END_RADIUS = 8
GUNSHOT_COLOR_IN = 7
GUNSHOT_COLOR_OUT = 10
